### PR TITLE
Svd - fixing building using linux and qt 5.9

### PR DESCRIPTION
**Pull request by gogo40**
Hi @PauloCarvalhoRJ 

In my environment  I had to fix some details to build gamma ray.

The main difference in code base is QVTKOpenglWidget. As in new vtk versions this is the recommended widget to be used with qt, I upgraded your support. (Also, in my environment QVTKWidget2 is already removed due deprecation).

### CODE REVIEW

**Comment by gogo40** [comment]
Also, I merged your updates in master.

**Comment by PauloCarvalhoRJ** [comment]
Is it possible to create a branch in this repository with your commits?  I'd like to compile and test it here in Windows before merging to master.  I can't get a pull request into my local repository.  Ok?

**Comment by gogo40** [comment]
of course

**Comment by gogo40** [comment]
https://github.com/gogo40/gammaray/tree/vtkopengl

**Comment by PauloCarvalhoRJ** [comment]
How do I copy that to my repository?

2018-01-13 18:28 GMT-02:00 Péricles Lopes Machado <notifications@github.com>
:

**Comment by PauloCarvalhoRJ** [comment]
Nevermind... I did a git fetch...

2018-01-13 19:08 GMT-02:00 Paulo Carvalho <paulo.r.m.carvalho@gmail.com>:

**Comment by gogo40** [comment]
You have to add a secondary remote in your local repository.

```
git remote add gogo40  git@github.com:gogo40/gammaray.git

git fetch gogo40
git merge gogo40/vtkopengl
```

**Comment by gogo40** [comment]
or

```
git checkout --track gogo40/vtkopengl
```

**Comment by PauloCarvalhoRJ** [comment]
Thanks for the tips!

2018-01-13 22:29 GMT-02:00 Péricles Lopes Machado <notifications@github.com>
:

**Comment by PauloCarvalhoRJ** [comment]
I merged the vtkopenl branch.  Can I delete this pull request?

**Comment by gogo40** [comment]
yes.

**Pull request merged**
